export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_FAIL = 'GET_WEATHER_FAIL';
export const GET_FORECAST_SUCCESS = 'GET_FORECAST_SUCCESS';
export const CURRENT_WEATHER_SUCCESS = 'CURRENT_WEATHER_SUCCESS';
export const SET_CURRENT_CITY = 'SET_CURRENT_CITY';
