export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_FAIL = 'GET_WEATHER_FAIL';
export const GET_WEATHER_OBJECTS = 'GET_WEATHER_OBJECTS';
export const FIND_RELEVANT_WEATHER_OBJECT = 'FIND_RELEVANT_WEATHER_OBJECT';
